package com.jaydeep.aimwise.data.model

import com.google.gson.JsonDeserializationContext
import com.google.gson.JsonDeserializer
import com.google.gson.JsonElement
import java.lang.reflect.Type

/**
 * Represents a single task within a day's plan.
 * 
 * @property description The task description text. Should not be empty.
 * @property isCompleted Whether the task has been completed by the user.
 *                       Defaults to false for new tasks.
 */
data class Task(
    val description: String,
    val isCompleted: Boolean = false
)

/**
 * Represents a daily plan within a goal's roadmap.
 * 
 * Each DayPlan contains the tasks to be completed on a specific day
 * and tracks the completion status of that day.
 * 
 * @property day The day number within the goal's duration (1-indexed).
 *               Must be positive (≥ 1) and not exceed the goal's durationDays.
 *               Defaults to 0 for uninitialized plans.
 *               Valid range: 1 to goal.durationDays.
 * @property tasks List of tasks to be completed on this day.
 *                 Empty list indicates no tasks assigned yet.
 *                 Tasks are ordered as generated by the AI.
 * @property status Current status of the day's plan.
 *                  Valid values: "pending" (not started), "in_progress" (some tasks completed),
 *                  "completed" (all tasks done), "skipped" (user skipped this day).
 *                  Defaults to "pending". Important for the skip feature.
 */
data class DayPlan(
    val day: Int = 0,
    val tasks: List<Task> = emptyList(),
    val status: String = "pending"
)

class DayPlanDeserializer : JsonDeserializer<DayPlan> {
    override fun deserialize(
        json: JsonElement,
        typeOfT: Type,
        context: JsonDeserializationContext
    ): DayPlan {
        val jsonObject = json.asJsonObject
        val day = jsonObject.get("day")?.asInt ?: 0
        val status = jsonObject.get("status")?.asString ?: "pending"
        
        // Handle tasks as either strings or Task objects
        val tasksArray = jsonObject.getAsJsonArray("tasks")
        val tasks = tasksArray.map { element ->
            if (element.isJsonPrimitive && element.asJsonPrimitive.isString) {
                // If it's a string, create a Task object
                Task(description = element.asString, isCompleted = false)
            } else {
                // If it's already a Task object, deserialize it
                context.deserialize<Task>(element, Task::class.java)
            }
        }
        
        return DayPlan(day = day, tasks = tasks, status = status)
    }
}